name: Release Backend Image to GitHub Container Registry
run-name: Backend Image ${{ inputs.image-name }} released to ghcr.io by @${{ github.actor }}

on:
  workflow_call:
    inputs:
      plone-version:
        required: true
        type: string
      use-mxdev:
        required: false
        type: boolean
        default: false
      image-name:
        required: true
        type: string
      context:
          required: true
          type: string
          default: "."
      dockerfile:
        required: true
        type: string
      build-args:
        required: false
        type: string
        default: ""
      platforms:
        required: true
        type: string
      load:
        required: false
        type: boolean
        default: false
      push:
        required: false
        type: boolean
        default: false
      is-latest:
        required: false
        type: boolean
        default: false
    secrets:
      registry-username:
        required: true
      registry-password:
        required: true

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ inputs.image-name }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=pep440,pattern={{version}}
            type=pep440,pattern={{major}}.{{minor}}.{{patch}}
            type=pep440,pattern={{major}}.{{minor}}
            type=pep440,pattern={{major}}
            type=sha
            type=raw,value=latest,enable=${{ inputs.is-latest }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.registry-username }}
          password: ${{ secrets.registry-password }}

      - name: "Run mxdev to get sources"
        if: inputs.use-mxdev
        run: |
          pip install mxdev
          cd ${{ inputs.context }} && mxdev -c mx.ini

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: ${{ inputs.platforms }}
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          build-args: |
            PLONE_VERSION=${{ inputs.plone-version }}
            ${{ inputs.build-args }}
          push: ${{ inputs.push && github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          load: ${{ inputs.load }}
